;;; tramp-rpc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;; Generated autoloads from tramp-rpc.el

(defconst tramp-rpc-method "rpc" "\
TRAMP method for RPC-based remote access.")

(defun tramp-rpc-file-name-p (vec-or-filename) "\
Check if VEC-OR-FILENAME is handled by TRAMP-RPC.
VEC-OR-FILENAME can be either a tramp-file-name struct or a filename string."
  (and-let* ((vec (tramp-ensure-dissected-file-name vec-or-filename)))
    (string= (tramp-file-name-method vec) tramp-rpc-method)))

(autoload 'tramp-rpc-file-name-handler "tramp-rpc" "\
Invoke TRAMP-RPC file name handler for OPERATION with ARGS.

\(fn OPERATION &rest ARGS)")

(with-eval-after-load 'tramp
  (when (fboundp 'tramp-register-foreign-file-name-handler)
    (unless (assoc tramp-rpc-method tramp-methods)
      (add-to-list 'tramp-methods `(,tramp-rpc-method)))
    (tramp-register-foreign-file-name-handler
     #'tramp-rpc-file-name-p #'tramp-rpc-file-name-handler)))

(register-definition-prefixes "tramp-rpc" '("tramp-rpc-" "with-tramp-rpc-batch"))

;;; Generated autoloads from tramp-rpc-deploy.el

(register-definition-prefixes "tramp-rpc-deploy" '("tramp-rpc-deploy-"))

;;; Generated autoloads from tramp-rpc-protocol.el

(register-definition-prefixes "tramp-rpc-protocol" '("tramp-rpc-protocol-"))

;;; End of scraped data

(provide 'tramp-rpc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tramp-rpc-autoloads.el ends here
